<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Пример API управления элементами списка
 *
 * API для создания, чтения, обновления и удаления элементов.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for itemsAddPost
     *
     * Добавление нового элемента.
     *
     */
    public function testItemsAddPost()
    {
    }

    /**
     * Test case for itemsDeleteIdDelete
     *
     * Удаление элемента.
     *
     */
    public function testItemsDeleteIdDelete()
    {
    }

    /**
     * Test case for itemsGet
     *
     * Получение списка элементов.
     *
     */
    public function testItemsGet()
    {
    }

    /**
     * Test case for itemsUpdateIdPut
     *
     * Обновление элемента.
     *
     */
    public function testItemsUpdateIdPut()
    {
    }
}
